::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: Name		:   makefile.bat																		::
:: Project	:   STM32F407VGTX																		::
:: Purpose	:  	Automatically build environment and generate output files.							::
:: Author	:   mehmtonrr																			::
:: Revision	:	23 Jan 2025 - initial version														::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

@echo off

set ARGS=%*

::set needed directories
set CUR_DIR=.
set ROOT_DIR=%CUR_DIR%.\..\..\External_Library\CTOOLS
::set tool path
set TOOL_DIR=%ROOT_DIR%\bin
::it will be used later in makefile!
set PATH=%TOOL_DIR%\make;%PATH%

set YEAR=%date:~10,4%
set MONTH=%date:~7,2%
set DAY=%date:~4,2%

echo > "%CC_LOG_FILE%"

echo ********************************************************************************	
echo *  Vestel Mobility Software Team Project Compilation 	  	 						
echo *  This file is automatically generated ! 											
echo *  Date of generation : %DAY%-%MONTH%-%YEAR%  										
echo ********************************************************************************	
echo.

:start
	@echo off
	echo 1. build_project
	echo 2. clean project
	echo 3. exit

	set choice=
	set /P CHOICE=Choose the process : 
	if not '%CHOICE%'=='' set choice=%CHOICE:~0,1%
	if '%CHOICE%'=='1' call :build_project
	if '%CHOICE%'=='2' call :clean_project
	if '%CHOICE%'=='3' call :exit
	echo.
	call :start
	
:build
	set START_TIME=%TIME%
	echo ********************************************************************************	
	echo STAGE: Building the project...														
	echo ********************************************************************************
	::-s, --silent, --quiet  Don't echo commands.
	::-j [N], --jobs[=N]  Allow N jobs at once; infinite jobs with no arg.
	make -s -j all 
	set END_TIME=%TIME%
	
	echo 'Finished building'
	echo Build Start Time:%START_TIME% 
	echo Build End Time:%END_TIME% 
	exit /b
	
:build_project
	call :build
	exit /b	
	
:clean_project
	echo ********************************************************************************	
	echo STAGE: Cleaning the project...														
	echo ********************************************************************************
	make -s -j clean 
	exit /b

	

:exit
	endlocal
	echo STAGE: Terminating the script... 
	pause
	exit