#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#:: Name		:   makefile.config																	 ::
#:: Project		:   STM32F407VGTX																	 ::
#:: Purpose		:  	Automatically build environment and generate output files.						 ::
#:: Author		:   mehmtonrr																		 ::
#:: Revision	:	27 Jan 2025 - initial version													 ::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


ACV_HDR_INCLUDES= SOURCE

ACV_SRC_INCLUDES= SOURCE STARTUP
